# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploy JDK8 version

on: workflow_dispatch
#  push:
#    branches: [ support/4.x-jdk8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: GPG Setup
      env:
        GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      #run: gpg-setup.sh
      run: printf "$GPG_KEY_BASE64" | base64 --decode > gpg.asc
